#!/bin/bash
source /usr/share/yunohost/helpers

ynh_script_progression "Backing up Warrior config and in-progress data..."
ynh_backup "$install_dir/docker-compose.yml"
ynh_backup "/etc/systemd/system/$app.service"
ynh_backup "$install_dir/data"
